# Generated by Django 2.2.5 on 2019-09-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singup',
            new_name='Signup',
        ),
    ]
